### ISSUE TITLE
tapCircleDiameter and different growth depending on longpress and normal touch

### ISSUE THREAD

**Issue by tskulbru** [bfeher/BFPaperButton#13]
According to http://www.google.com/design/spec/animation/responsive-interaction.html#responsive-interaction-surface-reaction any touches made to a paper element (which has touch feedback) should do a quick droplet animation and quickly fade out. The animation bounds should be the view's bounds. This behaviour is already implemented. However, if you look at the "touch ripple: drag in and out" you can see that the droplet animation fills the entire view. This isnt the case in today's code. If i press and hold on a corner in a BFPaperButton only half of the view gets filled, probably due to the fact that the diameter of the ripple is never larger than the view's width. Which then means if clicking on a corner, you only fill half of the visible view.

I may have overlooked something, but it looks to me to be a small oversight on your behalf.

**Comment by bfeher** [comment]
Hi tskulbru!

When I started this project, the Polymer-Project Paper Elements were still in beta, and the designs were changing each week. Believe it or not, the ripple used to only cover a portion of the control, not the full control. I had taken screen captures since there was not official documentation on how much the ripple should cover and was estimating based on those captures.

I see now that the default behavior has changed, but don't worry, I already have a solution for you :)

```
CGFloat tapCircleDiameter 
```
The CGFloat value representing the Diameter of the tap-circle. 
By default it will be the result of MAX(self.frame.width, self.frame.height). 
**tapCircleDiameterFull will calculate a circle that always fills the entire view.**
Any value less than or equal to tapCircleDiameterFull will result in default being used. 
The constants: tapCircleDiameterLarge, tapCircleDiameterMedium, 
and tapCircleDiameterSmall are also available for use.


You can set this to any positive float value, but it seems that the value **tapCircleDiameterFull** is the one you want.

Try this and let me know if it is still not behaving properly:
```
myButton.tapCircleDiameter = tapCircleDiameterFull;
```

I will make some changes to the readme file to make this more obvious in the future. Sorry if it was hard to find.

Thanks for using BFPaperButton! :)

**Comment by tskulbru** [comment]
Yes, i tested it with tapCircleDiameterFull, it fills the view which is better. But I don't think the animation is correct, it looks to me like it just fills the view and fades in from center. It doesn't look nor feel like the ripple animation on Android.

Other than than I'm very happy with the library, and i just hope that the library will be on par with the material design spec.

**Comment by bfeher** [comment]
Could you attach a gif of the issue? I don't quite understand what's happening. By default the circle should spawn from the tap location:

There is another property, 
BOOL rippleFromTapLocation 
A flag to set to YES to have the tap-circle ripple from point of touch. If this is set to NO, the tap-circle will always ripple from the center of the view. Default is YES.

If you are referring to the background fade, then have you tried to set the property:
```
.backgroundFadeColor = [UIColor clearColor];
```

**Comment by tskulbru** [comment]
Hehe, sorry for not being able to explain good enough. I'll see about giving you a gif (its a project for a client which i cant disclose a image for as of yet), but ill have to create a new project for it.

Thanks for the quick replies!

**Comment by bfeher** [comment]
No problem! I'm in Tokyo timezone so I might not always be this fast to respond, sorry.
