### ISSUE TITLE
Animation on button doesn't work when button's parent ViewController is embed into a container view (i.e child viewController)

### ISSUE THREAD

**Issue by bhargavms** [bfeher/BFPaperButton#26]
I have a viewcontroller, which has a container view, and this container view embeds(segue) a PageViewController, the 2nd page (which is another ViewController) in this PageViewController has the BFPaperButton. The animations don't work in this setup, but if I were to make the 2nd Page's ViewController as the `Is Initial View Controller` then the animations works perfectly, what is going on here??

**Comment by bhargavms** [comment]
Btw all the events are getting trigger correctly, I uncommented the NSLogs

```
2016-08-03 13:36:58.608 xxx[17251:1299425] Touch down handler
2016-08-03 13:36:58.609 xxx[17251:1299425] expanding a tap circle
```

As you can see they the touch down handler is called and the lift animation method is also called

**Comment by bhargavms** [comment]
I further isolated the issue, it seems this only happens when using a PageViewController and returning the ViewController containing the button in one of the data source delegate methods of PageViewController

**Comment by bfeher** [comment]
Hi @bhargavms !

Thanks for checkout out my control :)

The effect that you describe is quite common when dealing with certain types of parent views that delay the content touches of their child views. The solution is usually as simple as setting the parent view's property: `delaysContentTouches`.

I would remember this because 9 times out of 10, this is the culprit.

However, in the case of UIPageViewController, what you are seeing is the default behaviour of a **`UIQueuingScrollView`** which does not expose that property. An ugly but effective way to get around this is to dig through the subviews of your `UIPageViewController` until you get to one that has some `UIGestureRecognizers`, and setting `delaysTouchesBegan = NO`.

You could do this by simply running this code after you initialize your `UIPageViewController`:
```
NSArray *subviews = self.pageViewController.view.subviews;
NSArray *viewHierarchy = [@[self.pageViewController.view] arrayByAddingObjectsFromArray:subviews];
int i = 0;
for (UIView *viewToCheck in viewHierarchy) {
    for (UIGestureRecognizer *gestureRecognizer in viewToCheck.gestureRecognizers) {
        NSLog(@"%d gestureRecognizer: %@", i++, gestureRecognizer);
        gestureRecognizer.delaysTouchesBegan = NO;
    }
}
```

here is a quickly slapped together Swift version if you prefer:
```
let pageViewController: UIPageViewController = UIPageViewController(transitionStyle: .Scroll, navigationOrientation: .Horizontal, options: nil)
let subViews: [UIView] = pageViewController.view.subviews
var viewHierarchy: [UIView] = [pageViewController.view]
viewHierarchy.appendContentsOf(subViews)
var i = 0
for viewToCheck in viewHierarchy {
     viewToCheck.gestureRecognizers?.forEach { (recognizer) in
         print("viewToCheck isa \'\(viewToCheck.self)\'")
         for gestureRecognizer in viewToCheck.gestureRecognizers! {
             print("\(i) gestureRecognizer: \(gestureRecognizer)")
             i += 1
             gestureRecognizer.delaysTouchesBegan = false
          }
     }
}
```

**Comment by bhargavms** [comment]
Yep that fixed it fantastic dude !! thanks a bunch!
